### ISSUE TITLE
Bypass the geo-restriction

### ISSUE THREAD

**Issue by maxwellito** [solsticedhiver/arteVIDEOS#12]
Hello,
First, good job for this script, it's pretty cool!
Actually my request is not to report a bug but to include a new feature, if you agree. 
The idea is simple: bypass the geolocalisation and the time restriction. To can download any program from anywhere and anytime.
I've recently made a Chrome Extension to break these restrictions. It's quite simple, you just need to override a script from secure.arte.tv (I'm sure you already know that :-)
The problem is, I've never touched Python and BeautifulSoup. And if I understand, BeautifulSoup is just a parser, it means that no javascript is executed? Yes I'm a bit confused about the behavior of your script. But I would love to help and contribute.

Thanks

**Comment by solsticedhiver** [comment]
Sorry. Never noticed that issue.

May be a VPN is easier to work around the block
