### ISSUE TITLE
doesn't work anymore.

### ISSUE THREAD

**Issue by dominix** [solsticedhiver/arteVIDEOS#15]
since new design of arte.tv/plus7 arteVIDEOS crash directly after  "plus7" command.
too sad, it was my best help for missed programs on arte.

please, fix the new URL. Thanks in advance.

**Comment by AnnoyingTechnology** [comment]
Same here, a fix would be much appreciated

**Comment by yetanotherusera** [comment]
+AnnoyingTechnology +dominix you could use [youtube-dl] (https://rg3.github.io/youtube-dl/download.html) until the next version

**Comment by AnnoyingTechnology** [comment]
Thanks, I didn't know youtube-dl worked with Arte.

**Comment by solsticedhiver** [comment]
I don't know when, if ever, arteVIDEOS.py will be updated.

All I have found so far is the video api url http://www.arte.tv/guide/fr/plus/7/videos?zone=europe but I don't know to get something from that.

So I don't know how to get anymore a list of arte+7 videos to display it in arteVIDEOS.py

**Comment by AnnoyingTechnology** [comment]
Actually, I found out there was no need to go to youtube, this works : 
`$ youtube-dl http://concert.arte.tv/fr/avishai-cohen-trio-nancy-jazz-pulsations`

**Comment by solsticedhiver** [comment]
it's fixed thanks to https://github.com/known-as-bmf/plugin.video.arteplussept repo where I found relevant url

**programs* option still not working though for now and other minor issue
