### ISSUE TITLE
Code working with current ARTE website? 

### ISSUE THREAD

**Issue by chrmayer** [solsticedhiver/arteVIDEOS#19]
Hello, does this script still work with the current ARTE website?  If yes, I would be very grateful for some advice on what went wrong for me. 

python arteVIDEOS.py record --downloaddir=/Volumes/Macintosh\ HD/.../.../arte/ https://www.arte.tv/de/videos/103019-000-A/johann-sebastian-bach-matthaeus-passion/
Traceback (most recent call last):
  File "arteVIDEOS.py", line 732, in <module>
    main()
  File "arteVIDEOS.py", line 709, in main
    vid, stripped = args[1][len(VIDEO_URL):len(args[1])].split('/')
ValueError: too many values to unpack

**Comment by solsticedhiver** [comment]
Hello,
No, it has not been updated to latest site. So it's broken for quite a while.

I am gonna archive or close this repo.

I have no alternative to give you. The last time I searched for one, I couldn't find one.
But I think, something must exist.

May be woob-video-qt from woob sfotware suite.
